### ISSUE TITLE
Not working on Ubuntu and ST3

### ISSUE THREAD

**Issue by TimeBandit** [vinpac/sublime-simple-import#2]
Could you please test this on Ubuntu.
![st3-issue](https://cloud.githubusercontent.com/assets/2059850/17652131/f37bf7f0-626c-11e6-94b0-cc8718e0a183.png)

I am using ST3 build 3114

**Comment by vinpac** [comment]
What's happening?
Could you please take a screenshot of the console when you hit the command?

**Comment by TimeBandit** [comment]
I see nothing in the console. I think it's basically not searching the project folder and incorrectly returning the paths of my React components. This is what I am doing

- I want to import a menu component which is referenced in a jsx file. So my code looks like this
`
..
<span>
                <Menu />
                <div id="panel">
...
`

- I place the cursor over `<Menu />` and press `ctrl+alt+i'.

- Near the top of the fil I see `import Menu from 'menu';` instead of something like `import Menu from "../components/Menu.jsx";`

- So it looks like it not searching for it within the project root. 

- The file containing the component is name `Menu.jsx`and exports this `export default class Menu extends React.Component{...}`

- Thanks

 :)

**Comment by vinpac** [comment]
It looks like it's a problem with the extension.
Open you Preferences files ( Prefereces > Settings - User ). Add:
```
	"simple-import":
	{
		"excluded_directories":
		[
			"node_modules",
			".git"
		],
		"extensions":
		[
			"js",
			"jsx",
			"png",
			"jpg",
			"gif",
			"svg"
		],
		"remove_extensions":
		[
			"js",
			"jsx"
		]
	}
```
This will match the `jsx` extension and some others, like images.
Thanks for reporting the issue and I hope this solves your problem.
Peace!

**Comment by TimeBandit** [comment]
Hi, thanks but that didn’t work either. I noticed that simple import extensions were already there, although not for images, just js and jsx. I will try the branch that you sent and let you know :+1:

**Comment by TimeBandit** [comment]
Hi, manually installed the new branch. Same issue. It does not work out of the box.

**Comment by vinpac** [comment]
How many folders are open in the project?
If only one, then delete the SimpleImport folder at the packages folder ( Ctrl+Shift+P > Browse Packages ) and clone this project there. Version 2 will probably be better for you.

If it doesn't solve your problem, join the chat at https://gitter.im/sublime-simple-import/Lobby and we will solve your problem! :)

Again, thanks for helping.

**Comment by TimeBandit** [comment]
The project contains many folders. I should add that this was working at one point. I think it might have got broken when the new build of ST came out.

**Comment by vinpac** [comment]
I pushed a fix to this multiple folders problem. Could you test it and see if it solves your problem?
Just delete the plugin folder at the packages folder and clone branch master.

**Comment by TimeBandit** [comment]
Hi cloned the current master as you requested. What it did was to turn this:

`import React from 'react';`
`import { Meteor } from 'meteor/meteor';`
`// css`
`import "picnic/picnic.min.css";`
`import './App.less';`
`// components..`
`// import Menu from "../components/Menu.jsx";`

into this

`import React from 'react';`
`import { Meteor } from 'meteor/meteor';`
`// css`
`import Menu from '../components/Menu';`

So it sort of worked but removed my CSS and LESS import. Which is wrong :)

**Comment by vinpac** [comment]
Fixed: https://github.com/vinpac/sublime-simple-import/commit/45f47846d01ae0c34ac968c8176daa1b58526750
It was the regex that matches imports on view. Thanks for the reporting.
Closing the issue.

**Comment by TimeBandit** [comment]
Hi Vin, well this isn't what I reported last time but it's not doing anything either. Have I missed something? I cloned again from Master. Please advise.

**Comment by vinpac** [comment]
Hmm, could you please check the console for any error? These days I got an locale error after updating Sublime Text and this was causing not only Simple Import, but others plugins not to work. Is just Simple Import not working?
Join Gitter I will be there to help you!
https://gitter.im/sublime-simple-import/Lobby

**Comment by TimeBandit** [comment]
It's working now. You can close this. Thanks for the assistance. It really helped :+1:

**Comment by TimeBandit** [comment]
Sorry for ping ponging this but it worked once and then failed, this time i got an error in the console relating to the plugin.

```
/home/timebandit/Documents/projects/islamiccharities_code/.meteor/local/build/programs/server/npm/node_modules/xpath.js
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "/home/timebandit/.config/sublime-text-3/Packages/sublime-simple-import/SimpleImportCommand.py", line 86, in run
    exclude=path.join(path.join(self.view_dir_relpath, self.view_filename))
  File "/home/timebandit/.config/sublime-text-3/Packages/sublime-simple-import/lib/SimpleImport.py", line 135, in query
    exclude_file=exclude
  File "/home/timebandit/.config/sublime-text-3/Packages/sublime-simple-import/lib/SimpleImport.py", line 112, in findByValue
    matches = re.findall(interpreter.find_exports_regex, open(path.join(dirpath, filename)).read())
FileNotFoundError: [Errno 2] No such file or directory: '/home/timebandit/Documents/projects/islamiccharities_code/.meteor/local/build/programs/server/npm/node_modules/xpath.js'
```

**Comment by vinpac** [comment]
No problem! hahah More bugs you report, better the plugin will get.
This is an error when trying to find the modules you export. In theory it shouldn't happen because it crawls through the files in the project, so an `if` around this checking whether the files exists or not will solve it.
Thank you
